---
- hosts: butlertron
  become: yes
  vars_files:
    - 'vars.yml'

  handlers:
    - name: reload_systemd
      shell: systemctl daemon-reload


    - name: restart_butlertron
      service:
        name: butlertron
        state: restarted

  tasks:
    - name: Install apt packages
      apt:
        update_cache: true
        pkg:
          - default-jre

    - name: Create butlertron's directory
      file:
        path: /srv/butlertron
        state: directory
        mode: '0755'

    - name: Copy bot and unzip
      copy:
        src: ../build/libs/shadow-1.0-SNAPSHOT-all.jar
        dest: /srv/butlertron/butlertron.jar
        mode: '+x'
      notify:
        - restart_butlertron

    - name: Copy init script
      template:
        src: ./scripts/init.j2
        dest: /srv/butlertron/init.sh
        mode: '+x'
      notify:
        - restart_butlertron

    - name: Copy systemd service
      copy:
        src: scripts/butlertron.service
        dest: /etc/systemd/system/butlertron.service
        owner: root
        group: root
      notify:
        - reload_systemd
        - restart_butlertron